### ISSUE TITLE
https://www.youtube.com/watch?v=PMkiJIBBqFM  Neural Networks for Audio Effects Wolfram 

### ISSUE THREAD

**Issue by billyblackburn** [moddevices/mod-desktop-app#37]
https://www.youtube.com/watch?v=PMkiJIBBqFM  Neural Networks for Audio Effects Wolfram 
interesting videdo

**Comment by falkTX** [comment]
is that an issue? this is a place to report bugs as GH tickets, if you need to discuss something please do it on the mod audio forums, thanks!
